version: '3'
services:
  web:
    image: nginx:1.15.6
    ports:
      - "8010:80"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html/
  app:
    build: ./docker/php
    depends_on:
    - mysql
    volumes:
      - .:/var/www/html
  cron:
    build: ./docker/cron
    volumes:
     - .:/var/www/html
    links:
      - mysql
    depends_on:
      - app
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ask-publication
      MYSQL_USER: root
      MYSQL_PASSWORD: sunasterisk
      MYSQL_ROOT_PASSWORD: sunasterisk
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
